# Generated by Django 5.2.1 on 2025-07-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gatepass", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gatepass",
            name="qr_code",
            field=models.ImageField(blank=True, null=True, upload_to="qr_codes"),
        ),
    ]
