# Generated by Django 5.2.1 on 2025-07-30 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gatepass", "0003_remove_gatepass_actual_entry_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gatepass",
            name="alcohol_test_required",
            field=models.BooleanField(default=False),
        ),
    ]
