# Generated by Django 5.2.1 on 2025-07-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gatepass", "0004_gatepass_alcohol_test_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="gatepass",
            name="alcohol_test_photo",
            field=models.ImageField(blank=True, null=True, upload_to="alcohol_tests/"),
        ),
    ]
