# Generated by Django 5.2.1 on 2025-08-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gatepass", "0006_preapprovedvisitor"),
    ]

    operations = [
        migrations.AddField(
            model_name="gatepass",
            name="frequency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DAILY", "Daily"),
                    ("WEEKLY", "Weekly"),
                    ("MONTHLY", "Monthly"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="gatepass",
            name="is_recurring",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="gatepass",
            name="recurrence_end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
