from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import GatePassViewSet

router = DefaultRouter()
router.register(r'', GatePassViewSet, basename='gatepass') # Register GatePassViewSet

urlpatterns = [
    path('', include(router.urls)), # Include all URLs generated by the router
    # Any other specific paths for gatepass would go here if not handled by router actions
]