# Generated by Django 5.0.4 on 2024-05-13 10:00

from django.db import migrations

def populate_initial_data(apps, schema_editor):
    """
    Populates the Gate and Purpose tables with initial data.
    """
    Gate = apps.get_model('core_data', 'Gate')
    Purpose = apps.get_model('core_data', 'Purpose')

    # Initial gates
    gates_to_create = [
        Gate(name='Main Gate', location='Front Entrance'),
        Gate(name='Back Gate', location='Rear Exit'),
        Gate(name='Warehouse Gate', location='Loading Bay'),
    ]
    Gate.objects.bulk_create(gates_to_create, ignore_conflicts=True)

    # Initial purposes
    purposes_to_create = [
        Purpose(name='Visitor Entry'),
        Purpose(name='Staff Entry'),
        Purpose(name='Delivery/Receiving'),
        Purpose(name='Maintenance'),
        Purpose(name='Contractor Access'),
        Purpose(name='Official Business'),
    ]
    Purpose.objects.bulk_create(purposes_to_create, ignore_conflicts=True)

class Migration(migrations.Migration):

    dependencies = [
        ('core_data', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_initial_data),
    ]
