# Generated by Django 5.2.1 on 2025-07-28 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gate_operations", "0001_initial"),
        ("gatepass", "0003_remove_gatepass_actual_entry_time_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gatelog",
            options={
                "ordering": ["-timestamp"],
                "verbose_name": "Gate Log",
                "verbose_name_plural": "Gate Logs",
            },
        ),
        migrations.RenameField(
            model_name='gatelog',
            old_name='user',
            new_name='security_personnel',
        ),
        migrations.AddField(
            model_name='gatelog',
            name='scanned_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="gatelog",
            name="action",
            field=models.CharField(
                choices=[
                    ("entry", "Entry"),
                    ("exit", "Exit"),
                    ("scan_attempt", "Scan Attempt"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="gatelog",
            name="gate_pass",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="gatepass.gatepass",
            ),
        ),
        migrations.AlterField(
            model_name="gatelog",
            name="status",
            field=models.CharField(
                choices=[("success", "Success"), ("failure", "Failure")], max_length=50
            ),
        ),
    ]
