# Generated by Django 5.2.1 on 2025-08-06 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_data", "0001_initial"),
        ("gate_operations", "0002_alter_gatelog_options_remove_gatelog_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gatelog",
            name="gate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core_data.gate",
            ),
        ),
    ]
