// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBA2f_waj3pmC2fH6wZGG1qUUXc6okQr20',
    appId: '1:1022002944684:web:b5182ef0b7729096e81d09',
    messagingSenderId: '1022002944684',
    projectId: 'gatepass-597fd',
    authDomain: 'gatepass-597fd.firebaseapp.com',
    storageBucket: 'gatepass-597fd.firebasestorage.app',
    measurementId: 'G-F3P407F0TQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1vcu4YZpHJv6HQk8AWzWG4NnBOT4Dex4',
    appId: '1:1022002944684:android:574d20988b46f47de81d09',
    messagingSenderId: '1022002944684',
    projectId: 'gatepass-597fd',
    storageBucket: 'gatepass-597fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBunWXXcTHp4AmFMSXZSPVX_OBi0ceTpp0',
    appId: '1:1022002944684:ios:927252b0718e5474e81d09',
    messagingSenderId: '1022002944684',
    projectId: 'gatepass-597fd',
    storageBucket: 'gatepass-597fd.firebasestorage.app',
    iosBundleId: 'com.example.gatepassApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBunWXXcTHp4AmFMSXZSPVX_OBi0ceTpp0',
    appId: '1:1022002944684:ios:927252b0718e5474e81d09',
    messagingSenderId: '1022002944684',
    projectId: 'gatepass-597fd',
    storageBucket: 'gatepass-597fd.firebasestorage.app',
    iosBundleId: 'com.example.gatepassApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBA2f_waj3pmC2fH6wZGG1qUUXc6okQr20',
    appId: '1:1022002944684:web:264d3db9730ff403e81d09',
    messagingSenderId: '1022002944684',
    projectId: 'gatepass-597fd',
    authDomain: 'gatepass-597fd.firebaseapp.com',
    storageBucket: 'gatepass-597fd.firebasestorage.app',
    measurementId: 'G-XVD54LV596',
  );
}
