# Generated by Django 5.2.1 on 2025-07-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("license_number", models.CharField(max_length=255, unique=True)),
                ("contact_details", models.CharField(max_length=255)),
                ("address", models.TextField()),
                ("status", models.CharField(max_length=255)),
            ],
        ),
    ]
