# Generated by Django 5.2.1 on 2025-07-25 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core_data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vehicle_number", models.CharField(max_length=255, unique=True)),
                ("make", models.CharField(max_length=255)),
                ("model", models.CharField(max_length=255)),
                ("capacity", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=255)),
                ("registration_date", models.DateField()),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core_data.vehicletype",
                    ),
                ),
            ],
        ),
    ]
